### ISSUE TITLE
Delete Test Users

### ISSUE THREAD

**Issue by Felli** [victorpdiez/humhub-module-performance_insights#1]
At the moment it does create the test users but it doesn't delete the test users once selected to do so. But I do like the idea behind this module, and it does work for performance testing. :+1:

**Comment by joseph-kuruvilla** [comment]
hello, Please let me know what error are you getting while deleting the users.if you created 10k users or above. it takes a long while to complete the deleting process.

**Comment by victorpdiez** [comment]
Hi @Felli could you help us wiht the problem with creating users. Thanks a lot!

**Comment by Felli** [comment]
@victorpdiez at the moment I've got a lot of work on my plate, although when I have time I'll look into this module more and if I find anything I'll send a pull request your way. :smiley:

**Comment by Buliwyfa** [comment]
ok great thanks and good luck with the work :)

**Comment by victorpdiez** [comment]
thanks!
